{{- if .Values.config.basicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runtime.name" . }}-auth
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  auth: {{ .Values.config.basicAuth | b64enc }}
{{- end }}