kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "runtime.name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  php.ini: {{ .Values.config.php | quote }}
  msmtp.conf: {{ .Values.config.msmtp | quote }}
  supervisor.conf: {{ .Values.config.supervisor | quote }}
