apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runtime.name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runtime.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:          
            - name: "RUNTIME_USER_NAME"
              value: {{ .Release.Name | quote }}
            - name: "RUNTIME_USER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: userPassword
                  name: {{ include "runtime.name" . }}
            - name: "RESTIC_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: backupPassword
                  name: {{ include "runtime.name" . }}
          volumeMounts:
            - mountPath: /home/runtime
              name: data
              {{- if not .Values.config.localPath }}
              subPath: home
              {{- end }}
      volumes:
        {{- if .Values.config.localPath }}
        - name: data
          hostPath:
            path: {{ .Values.config.localPath }}
            type: DirectoryOrCreate
        {{- else }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "runtime.name" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
