apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runtime.name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        runtime.sitepilot.io/checksum: {{ include (print $.Template.BasePath "/config.yml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runtime.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Release.Name | quote }}
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /sitepilot/ping/
              port: http
          readinessProbe:
            httpGet:
              path: /sitepilot/ping/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "RUNTIME_USER_NAME"
              value: {{ .Release.Name | quote }}
            - name: "RUNTIME_USER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: userPassword
                  name: {{ include "runtime.name" . }}
            {{- range .Values.extraEnvVars }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /home/runtime
              {{- if not .Values.config.nodePath }}
              subPath: home
              {{- end }}
            - mountPath: /opt/runtime/config.yml
              name: config
              subPath: runtime
      volumes:
        {{- if .Values.config.nodePath }}
        - name: data
          hostPath:
            path: {{ .Values.config.nodePath }}
            type: DirectoryOrCreate
        {{- else }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "runtime.name" . }}
        {{- end }}
        - name: secret
          secret:
            secretName: {{ include "runtime.name" . }}
        - name: config
          secret:
            secretName: {{ include "runtime.name" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
