{{- if not .Values.config.localPath }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "runtime.name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.volume.storage }}"
{{- end }}