apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runtime.name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  userPassword: {{ .Values.config.userPassword | b64enc }}
