apiVersion: v1
kind: Service
metadata:
  name: {{ include "runtime.name" . }}-web
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "runtime.selectorLabels" . | nindent 4 }}
