{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "runtime.name" . }}-ssh
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "runtime.selectorLabels" . | nindent 4 }}
{{- end }}