replicaCount: 1

config:
  userPassword: ""
  backupPassword: ""
  basicAuth: ""
  authorizedKeys: ""

image:
  repository: ghcr.io/sitepilot/runtime
  pullPolicy: IfNotPresent
  tag: ""

volume:
  storage: 5G

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: "runtime.test"
      paths:
        - path: /
  tls: []

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
