---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "redis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  password
                  name: {{ include "redis.fullName" . }}
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: redis-data
              subPath: {{ include "redis.name" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: redis-data
          hostPath:
            path: {{ .Values.localPath }}
            type: DirectoryOrCreate
      {{- if .Values.node }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ .Values.node }}"
      {{- end }}