apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  {{- if .Values.nodePort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
      {{- if .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
