config:
  database: ""
  userName: ""
  userPassword: ""
  rootPassword: ""

image:
  repository: mariadb
  pullPolicy: IfNotPresent
  tag: ""

volume:
  storage: 10G

service:
  type: ClusterIP

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
