config:
  database: "stack"
  userName: "captain"
  userPassword: "secret"
  rootPassword: "supersecret"

image:
  repository: mariadb
  pullPolicy: IfNotPresent
  tag: ""

volume:
  storage: 10G

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
