---
type: app

pool: null

node: null

localPath: null

storage: 5Gi

image:
  repository: ghcr.io/sitepilot/runtime
  pullPolicy: Always
  tag: latest

service:
  ssh:
    port: 0

ingress:
  enabled: true
  rootDomain: "sitepilot.dev"
  annotations: {}
#  hosts:
#    - host: 'domain.com'

resources:
  # limits:
  #  cpu: 500m
  #  memory: 256Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

runtime:
  server: {}
