apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailhog.name" . }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8025
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mailhog.selectorLabels" . | nindent 4 }}
