kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mariadb.name" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.volume.storage }}"
