node: undefined

nodePort: null

localPath: /opt/sitepilot/services/mysql

image:
  repository: bitnami/mysql
  pullPolicy: IfNotPresent
  tag: "8.0"

auth:
  database: sitepilot
  username: captain
  password: secret
  rootPassword: supersecret

resources:
  # limits:
  #  cpu: 500m
  #  memory: 256Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
