
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.name" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  userPassword: "{{ .Values.config.userPassword | b64enc }}"
  rootPassword: "{{ .Values.config.rootPassword | b64enc }}"