replicaCount: 1

config:
  basicAuth: ""

image:
  repository: mailhog/mailhog
  pullPolicy: IfNotPresent
  tag: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: "mailhog.test"
      paths:
        - path: /
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
