---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: ssh
              containerPort: 2222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/-/health/"
              port: http
          readinessProbe:
            httpGet:
              path: "/-/health/"
              port: http
          env:
            - name: "UPDATE_FILE_PERMISSIONS"
              value: "true"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/sitepilot/app
              name: app-data
              {{- if or (.Values.pool) (.Values.localPath) }}
              subPath: apps/{{ include "app.name" . }}
              {{- else }}
              subPath: data
              {{- end }}
            - name: app-config
              mountPath: /opt/sitepilot/config
      affinity:
      {{- if .Values.pool }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "pool.sitepilot.io/name"
                    operator: "In"
                    values:
                      - "{{ .Values.pool }}"
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- if .Values.node }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ .Values.node }}"
      {{- end }}
      volumes:
        {{- if .Values.localPath }}
        - name: app-data
          hostPath:
            path: {{ .Values.localPath }}
            type: Directory
        {{- else if .Values.pool }}
        - name: app-data
          persistentVolumeClaim:
            claimName: pool-{{ .Values.pool }}
        {{- else }}
        - name: app-data
          persistentVolumeClaim:
            claimName: "{{ include "app.fullName" . }}"
        {{- end }}
        - name: app-config
          secret:
            secretName: {{ include "app.fullName" . }}
